name: Generate Course with Lupo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Lupo Action
        run: |
          curl -L -X POST http://projectbuilds.lupo.ai:5000/api/action \
          -H "Content-Type: application/json" \
          -d '{"repo":"'$repo'","branch":"'$branch'","actor":"'$actor'"}'
        env:
          repo: ${{ github.repository }}
          branch: ${{ github.ref }}
          actor: ${{ github.actor }}
